"""update meal

Revision ID: 2ae038676aa6
Revises: 48d7b981f685
Create Date: 2015-10-24 14:58:14.017000

"""

# revision identifiers, used by Alembic.
revision = '2ae038676aa6'
down_revision = '48d7b981f685'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('is_selected', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'is_selected')
    ### end Alembic commands ###
