"""add meal zipcode

Revision ID: 54a5edc457d2
Revises: 335fb8abf83f
Create Date: 2015-10-24 14:49:31.310000

"""

# revision identifiers, used by Alembic.
revision = '54a5edc457d2'
down_revision = '335fb8abf83f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zipcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chef_id', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_zipcode',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('zipcode_id', sa.Integer(), nullable=False),
    sa.Column('begin_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.ForeignKeyConstraint(['zipcode_id'], ['zipcode.id'], ),
    sa.PrimaryKeyConstraint('meal_id', 'zipcode_id')
    )
    op.drop_index('ix_user_nickname', table_name='user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=1)
    op.drop_table('meal_zipcode')
    op.drop_table('meal')
    op.drop_table('zipcode')
    ### end Alembic commands ###
