"""add address and phone fields to orders model

Revision ID: cad06c3b298
Revises: c206d33949d
Create Date: 2015-10-24 21:04:08.023000

"""

# revision identifiers, used by Alembic.
revision = 'cad06c3b298'
down_revision = 'c206d33949d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('order', sa.Column('phone', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'phone')
    op.drop_column('order', 'address')
    ### end Alembic commands ###
